include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    use_super_parameters: true
    curly_braces_in_flow_control_structures: true
    unnecessary_const: true
    annotate_overrides: true
    avoid_init_to_null: true
    prefer_final_fields: true
    prefer_final_locals: true
