// lib/features/auth/presentation/login/login_notifier.dart

import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:ace/features/auth/services/student_auth_service.dart';
import 'package:ace/features/auth/services/admin_auth_service.dart';
import 'package:ace/features/auth/presentation/login/login_state.dart';

part 'login_notifier.g.dart'; // Generated by Riverpod

@riverpod
class LoginNotifier extends _$LoginNotifier {
  // Use the service defined in the provider's build method later if needed,
  // but for simplicity, we initialize it directly here.
  late final dynamic _authService;

  // 1. Initial State and Service Initialization
  @override
  LoginState build({UserType userType = UserType.student}) {
    // Initialize the correct service based on the UserType
    // Note: AdminAuthService and StudentAuthService are instantiated here.
    if (userType == UserType.admin) {
      _authService = AdminAuthService();
    } else {
      _authService = StudentAuthService();
    }

    return LoginState(userType: userType);
  }

  // 2. State Mutators (Update functions using copyWith)
  // This function acts as the generic ID/Username setter for both user types.
  void setStudentId(String id) {
    state = state.copyWith(studentId: id.trim(), errorMessage: '');
  }

  void setPassword(String pass) {
    state = state.copyWith(password: pass, errorMessage: '');
  }

  void togglePasswordVisibility() {
    state = state.copyWith(isPasswordVisible: !state.isPasswordVisible);
  }

  // 3. Login Execution Logic
  Future<bool> login() async {
    // Check if the form is valid using the getter defined in LoginState
    if (!state.isValidForm) {
      state = state.copyWith(errorMessage: 'Please enter all required fields.');
      return false;
    }

    // Set loading state
    state = state.copyWith(isLoading: true, errorMessage: '');

    try {
      // Check the user type and pass the parameter name the service expects.
      if (state.userType == UserType.admin) {
        await _authService.login(
          // AdminAuthService expects 'adminId'
          adminId: state.studentId, // state.studentId holds the Admin ID
          password: state.password,
        );
      } else {
        await _authService.login(
          // StudentAuthService expects 'studentId'
          studentId: state.studentId,
          password: state.password,
        );
      }

      // Success
      state = state.copyWith(isLoading: false);
      return true;
    } catch (e) {
      String message = 'An unexpected error occurred during login.';

      // Enhanced error checking for specific services
      if (e.toString().contains(AdminAuthService.wrongCredentialsError)) {
        message = 'Wrong Admin ID or password.';
      } else if (e
          .toString()
          .contains(StudentAuthService.wrongCredentialsError)) {
        message = 'Wrong Student ID or password.';
      } else if (e.toString().contains('network-request-failed')) {
        message = 'Network error. Check your connection.';
      }

      // Failure
      state = state.copyWith(isLoading: false, errorMessage: message);
      return false;
    }
  }
}
