// lib/features/admin_dashboard/presentation/class_creation_dialog.dart

import 'package:flutter/material.dart';
import 'package:ace/core/constants/app_colors.dart';
import 'package:ace/models/classroom.dart';
import 'package:ace/models/user.dart';
import 'package:ace/services/user_service.dart';

// Mock list of available banner paths for the form (since we don't have file upload)
const List<String> _mockBannerPaths = [
  'assets/images/banner/banner1.jpg',
  'assets/images/banner/banner2.jpg',
  'assets/images/banner/banner3.jpg',
  'assets/images/banner/banner4.jpg',
  'assets/images/banner/banner5.jpg',
  'assets/images/banner/banner6.jpg',
  'assets/images/banner/banner7.jpg',
  'assets/images/banner/banner8.jpg',
];

class ClassCreationDialog extends StatefulWidget {
  // Callback function to handle the new class object when the form is submitted
  final Function(Classroom) onClassCreated;

  const ClassCreationDialog({super.key, required this.onClassCreated});

  @override
  State<ClassCreationDialog> createState() => _ClassCreationDialogState();
}

class _ClassCreationDialogState extends State<ClassCreationDialog> {
  final _formKey = GlobalKey<FormState>();
  String _className = '';
  String _description = '';
  String _creator = '';
  // Default to the first path
  String _selectedBannerPath = _mockBannerPaths.first;

  final UserService _userService = UserService();
  List<User> _teachers = [];
  String? _selectedTeacherId;

  @override
  void initState() {
    super.initState();
    _fetchTeachers();
  }

  Future<void> _fetchTeachers() async {
    final teachers = await _userService.fetchAllTeachers();
    if (mounted) {
      setState(() {
        _teachers = teachers;
      });
    }
  }

  void _submitForm() {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();

      // Create a temporary Classroom object. The classId will be generated by Firebase.
      final newClass = Classroom(
        classId: '', // Placeholder, as Firebase will generate the real ID
        className: _className,
        description: _description,
        creator: _creator,
        bannerImgPath: _selectedBannerPath,
        teacherId: _selectedTeacherId,
      );

      widget.onClassCreated(newClass);
      Navigator.of(context).pop(); // Close the dialog
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Create New Class'),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              TextFormField(
                decoration: const InputDecoration(labelText: 'Class Name'),
                validator: (value) =>
                    value!.isEmpty ? 'Please enter a class name' : null,
                onSaved: (value) => _className = value!,
              ),
              TextFormField(
                decoration: const InputDecoration(
                    labelText: 'Description (e.g., Topic)'),
                validator: (value) =>
                    value!.isEmpty ? 'Please enter a description' : null,
                onSaved: (value) => _description = value!,
                maxLines: 2,
              ),
              // Replaced manual text field with Dropdown for teachers
              if (_teachers.isEmpty) ...[
                const Text('Loading Teachers... or No Teachers Found',
                    style: TextStyle(color: Colors.grey)),
                const SizedBox(height: 10),
              ] else ...[
                DropdownButtonFormField<String>(
                  items: _teachers.map((t) {
                    return DropdownMenuItem(
                      value: t.userId,
                      child: Text(t.fullname),
                    );
                  }).toList(),
                  onChanged: (val) {
                    setState(() {
                      _selectedTeacherId = val;
                      // Also set creator name for display consistency
                      final teacher =
                          _teachers.firstWhere((t) => t.userId == val);
                      _creator = teacher.fullname;
                    });
                  },
                  decoration:
                      const InputDecoration(labelText: 'Assign Teacher'),
                  validator: (val) =>
                      val == null ? 'Please select a teacher' : null,
                ),
              ],
              const SizedBox(height: 15),
              // Dropdown to select a banner path
              DropdownButtonFormField<String>(
                decoration: const InputDecoration(
                  labelText: 'Select Banner Image',
                  border: OutlineInputBorder(),
                ),
                value: _selectedBannerPath,
                items: _mockBannerPaths.map((String path) {
                  return DropdownMenuItem<String>(
                    value: path,
                    child: Text(path.split('/').last), // Show just the filename
                  );
                }).toList(),
                onChanged: (String? newValue) {
                  setState(() {
                    _selectedBannerPath = newValue!;
                  });
                },
                validator: (value) =>
                    value == null ? 'Please select a banner' : null,
              ),
              const SizedBox(height: 20),
              // Show a small preview of the selected banner
              if (_selectedBannerPath.isNotEmpty)
                Container(
                  height: 100,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(8),
                    image: DecorationImage(
                      image: AssetImage(_selectedBannerPath),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
            ],
          ),
        ),
      ),
      actions: <Widget>[
        TextButton(
          child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
        ElevatedButton(
          style: ElevatedButton.styleFrom(
            backgroundColor: ColorPalette.secondary,
            foregroundColor: Colors.white,
          ),
          onPressed: _submitForm,
          child: const Text('Create'),
        ),
      ],
    );
  }
}
